name: voila-gallery-country-indicators
channels:
- conda-forge
dependencies:
- matplotlib>=3.7.1
- pandas
- ipywidgets
- jupyterlab>=3.1
- voila>=0.2.11
- IPython>=8.12.0
- jupyter_client>=7.4.1
- jupyter_core>=5.3.0
- jupyterlab>=3.6.3
- notebook>=6.5.4
